services:
  mysql:
    image: mysql:8.0
    container_name: fynup_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fynup_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./back
    container_name: fynup_backend
    restart: always
    environment:
      PORT: 4001
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      TOKEN_EXPIRATION: 4h
    ports:
      - "${BACKEND_PORT}:4001"
    networks:
      - fynup_network

  frontend:
    build: ./front
    container_name: fynup_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:4001
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - fynup_network

networks:
  fynup_network:
    driver: bridge

volumes:
  mysql_data: