services:
  mysql:
    image: mysql:8.0
    container_name: coinmaster_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - coinmaster_mysql_data:/var/lib/mysql
      - ./back/db/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - coinmaster_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./back
    container_name: coinmaster_backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: 4001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      TOKEN_EXPIRATION: 4h
    ports:
      - "${BACKEND_PORT}:4001"
    networks:
      - coinmaster_network

  frontend:
    build: ./front
    container_name: coinmaster_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:4001
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - coinmaster_network

networks:
  coinmaster_network:
    driver: bridge

volumes:
  coinmaster_mysql_data: